name: Sign
author: Microsoft Corporation
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  azureCredentialsJson:
    description: Azure Credentials secret
    required: true
  pathToFiles:
    description: The path to the files to be signed
    required: true
  timestampService:
    description: The URI of the timestamp server
    required: false
    default: http://timestamp.digicert.com
  digestAlgorithm:
    description: The digest algorithm to use for signing and timestamping
    required: false
    default: SHA256
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '7b7d'
runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      env:
        _azureCredentialsJson: ${{ inputs.azureCredentialsJson }}
        _pathToFiles: ${{ inputs.pathToFiles }}
        _timestampService: ${{ inputs.timestampService }}
        _digestAlgorithm: ${{ inputs.digestAlgorithm }}
        _parentTelemetryScopeJson: ${{ inputs.parentTelemetryScopeJson }}
      run: |
        $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
        try {
          ${{ github.action_path }}/Sign.ps1 -AzureCredentialsJson $ENV:_azureCredentialsJson -PathToFiles $ENV:_pathToFiles -TimestampService $ENV:_timestampService -digestAlgorithm $ENV:_digestAlgorithm -ParentTelemetryScopeJson $ENV:_parentTelemetryScopeJson
        }
        catch {
          Write-Host "::ERROR::Unexpected error when running action. Error Message: $($_.Exception.Message.Replace("`r",'').Replace("`n",' ')), StackTrace: $($_.ScriptStackTrace.Replace("`r",'').Replace("`n",' <- '))";
          exit 1
        }
branding:
  icon: terminal
  color: blue
