name: Powershell Script
author: Kennet Lindberg
inputs:
  token:
    description: The GitHub token running the action
    required: false
    default: ${{ github.token }}  
runs:
  using: composite
  steps:
    - name: run
      shell: PowerShell
      env:
        _token: ${{ inputs.token }}
      run: try { ${{ github.action_path }}/DeployOnPremise.ps1 -token $ENV:_token } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
branding:
  icon: terminal
  color: blue
